name: "tpch_medallion"
version: "1.0.0"
config-version: 2

model-paths: ["tpch_medallion_dbt/models"]
snapshot-paths: ["tpch_medallion_dbt/snapshots"]
macro-paths: ["macros"]                     
#seed-paths: ["seeds"]                       
#test-paths: ["tests"]                       

models:
  tpch_medallion:
    +database: DEMO_DB
    +materialized: table

    bronze:
      +schema: BRONZE
      +materialized: view
      +tags: ["bronze"]

    silver:
      +schema: SILVER
      +materialized: table
      +tags: ["silver"]

    gold:
      +schema: GOLD
      +materialized: table
      +tags: ["gold"]

snapshots:
  +target_database: DEMO_DB
  +target_schema: SNAPSHOTS
