name: "tpch_medallion"
version: "1.0.0"
config-version: 2

# dbt Cloud manages the profile; this value is unused in Cloud.
profile: "default"

models:

  tpch_medallion:
    +materialized: table
    +database: DEMO_DB   

    sources:
      +schema: bronze
      +database: DEMO_DB

    bronze:
      +schema: bronze
      +tags: ["bronze"]
      +materialized: view
      +database: DEMO_DB

    silver:
      +schema: silver
      +tags: ["silver"]
      +materialized: table
      +database: DEMO_DB

    gold:
      +schema: gold
      +tags: ["gold"]
      +materialized: table
      +database: DEMO_DB

snapshots:
  +target_database: DEMO_DB
  +target_schema: SNAPSHOTS
